events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # 1. Redirection automatique HTTP (Port 80) vers HTTPS
    server {
        listen 80;
        server_name localhost; 
        return 301 https://$host$request_uri;
    }

    # 2. Le vrai serveur HTTPS (Port 443)
    server {
        listen 443 ssl;
        server_name localhost;

        # Emplacement de tes certificats (montés via le docker-compose)
        ssl_certificate /etc/nginx/ssl/certification.crt;
        ssl_certificate_key /etc/nginx/ssl/cle.key;

        # Protocoles TLS sécurisés pour la soutenance
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # On renvoie le trafic chiffré vers ton Dashboard Flask
        location / {
            # CORRECTIF : On cible le VRAI container_name défini dans Docker
            proxy_pass http://flask_soc_app:5000; 

            # Entêtes indispensables pour transmettre les vraies IP à Fail2Ban
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}